CREATE DATABASE BMS_DB1;
USE BMS_DB1;
SHOW databases;

CREATE TABLE CUSTOMER_PERSONAL_INFO (
	CUSTOMER_ID VARCHAR(5),
    CUSTOMER_NAME VARCHAR(30),
    DATE_OF_BIRTH DATE ,
    EMAIL VARCHAR(30),
    GENDER CHAR(1) ,
    MARITAL_STATUS VARCHAR(10),
    COUNTRY VARCHAR(10),
    PRIMARY KEY(CUSTOMER_ID));
    
    SHOW TABLES;
    
CREATE TABLE CUSTOMER_REFERENCE_INFO (
	CUSTOMER_ID VARCHAR(5),
	ACCOUNT_NAME VARCHAR(20),
    ACCOUNT_NUMBER BIGINT(16),
    PRIMARY KEY (CUSTOMER_ID));
    
CREATE TABLE ACCOUNT_INF0 (
	ACCOUNT_NUMBER BIGINT(16),
    CUSTOMER_ID VARCHAR(5),
    ACCOUNT_DATE DATE,
    REGRISTRATION_DATE DATE,
    ACTIVATION_DATE DATE,
    INITIAL_DEPOSIT  BIGINT(20),
    PRIMARY KEY (ACCOUNT_NUMBER , CUSTOMER_ID));
    

    